# Generated by Django 5.0 on 2023-12-23 19:07

import baseapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=baseapp.models.generate_images_upload_path)),
                ('specialization', models.CharField(max_length=255)),
                ('experience', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('patients', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('telegram_user', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=baseapp.models.generate_images_upload_path)),
                ('phone', models.CharField(max_length=15)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.region')),
            ],
        ),
    ]
