# Generated by Django 5.0 on 2024-02-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_userinfo_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
